# Generated by Django 5.2.4 on 2025-08-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('ftp', 'FTP'), ('tcp', 'TCP'), ('udp', 'UDP')], max_length=10)),
                ('url', models.URLField(max_length=255)),
                ('port', models.PositiveIntegerField()),
            ],
        ),
    ]
