# Generated by Django 5.2.4 on 2025-08-02 19:37

import registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='application',
            name='port',
            field=models.PositiveIntegerField(validators=[registry.models.validate_port_range]),
        ),
    ]
